# THONG TIN CONG TY (BEN A) DUNG CHO HOP DONG
company_name= C\u00f4ng Ty TNHH P\u01a1 Bread
company_address=T\u1ea7ng 5, T\u00f2a nh\u00e0 FPT, Khu C\u00f4ng Ngh\u1ec7 Cao H\u00f2a L\u1ea1c, Th\u1ea1ch Th\u1ea5t, H\u00e0 N\u1ed9i
company_phone=0999.999.999
company_tax_code=0101248141
company_rep_name= Mr. Ki\u00ean B\u00e1
company_position=T\u1ed5ng Gi\u00e1m \u0110\u1ed1c
tax_code=66669999